find_path(HDFS_INCLUDES NAMES hdfs.h  HINTS ${HDFS_DIR}/include $ENV{HDFS_DIR}/include)
find_library(HDFS_LIB NAMES hdfs HINTS ${HDFS_DIR}/lib/native $ENV{HDFS_DIR}/lib/native)


GET_FILENAME_COMPONENT(HDFS_LIB_DIR ${HDFS_LIB} PATH)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Hdfs DEFAULT_MSG HDFS_LIB HDFS_LIB_DIR HDFS_INCLUDES)


